server:
  port: 8081
#  parametrizar puerto
spring:
  main:
    allow-circular-references: true
  application:
    name: crm_db
  datasource:
    url: jdbc:${{ MySQL.MYSQL_URL }}
#    parametrizar localhost
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
#      driver: com.mysql.cj.jdbc.Driver
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
jwt:
  secret: MyCookieJar123
springdoc:
  swagger-ui:
    path: /crm_db.html
    operationsSorter: method
